/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 09-Jun-2021 19:44:50 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "Address"
(
	"Lines" varchar(50) NOT NULL,
	"City" varchar(50) NOT NULL,
	"Postcode" varchar(10) NOT NULL,
	"AddressID" integer NOT NULL
)
;

CREATE TABLE "Applicationforpayment"
(
	"Jobid" varchar(50) NOT NULL,
	"Timestamp" timestamp without time zone NOT NULL,
	"LastPrinted" timestamp without time zone,
	"Sequencenumber" integer NOT NULL,
	"ApplicationforpaymentID" integer NOT NULL
)
;

CREATE TABLE "Auditrow"
(
	"Loggedinuser" varchar(200) NOT NULL,
	"Who" varchar(50) NOT NULL,
	"Command" varchar(50) NOT NULL,
	"Timestamp" timestamp with time zone NOT NULL,
	"Parameters" text,
	"AuditrowID" integer NOT NULL,
	"CustomerID" integer,
	"UsergroupID" integer,
	"JobID" integer,
	"AfpID" integer
)
;

CREATE TABLE "Creditcheck"
(
	"Number" varchar(50) NOT NULL,
	"Who" varchar(50) NOT NULL,
	"Timestamp" timestamp with time zone NOT NULL,
	"JobID" integer NOT NULL,
	"CreditcheckID" integer NOT NULL,
	"UsergroupID" integer NOT NULL
)
;

CREATE TABLE "Customer"
(
	"Name" varchar(50) NOT NULL,
	"AddressId" integer NOT NULL,
	"CustomerID" integer NOT NULL
)
;

CREATE TABLE "Door"
(
	"Type" varchar(50),
	"Width" numeric,
	"Height" numeric,
	"Costprice" numeric,
	"Sellprice" numeric,
	"Colour" varchar(50),
	"Stage" varchar(50),
	"DoorID" integer NOT NULL,
	"LineitemID" integer,
	"DoortypeID" integer
)
;

CREATE TABLE "Doortype"
(
	"Value" varchar(50) NOT NULL,	-- end Type
	"Other" varchar(50),
	"DoortypeID" integer NOT NULL
)
;

CREATE TABLE "Job"
(
	"Id" varchar(50) NOT NULL,
	"CustomerId" integer NOT NULL,
	"Sitecontact" varchar(50) NOT NULL,
	"Sitecontactphone" varchar(50),
	"Siteaddressid" integer NOT NULL,
	"Qscontact" varchar(50),
	"Qscontactphone" text,
	"Stage" text NOT NULL,
	"JobID" integer NOT NULL
)
;

CREATE TABLE "Jobapproval"
(
	"UserGroupId" integer NOT NULL,
	"Timestamp" timestamp with time zone NOT NULL,
	"JobapprovalID" integer NOT NULL,
	"JobID" integer NOT NULL
)
;

CREATE TABLE "Lineapplicationforpayment"
(
	"Percent" integer NOT NULL,
	"Grossamount" numeric NOT NULL,
	"LineapplicationforpaymentID" integer NOT NULL,
	"Nettamount" numeric NOT NULL,
	"ApplicationforpaymentID" integer NOT NULL,
	"LineItemId" integer NOT NULL
)
;

CREATE TABLE "Lineitem"
(
	"LineitemID" integer NOT NULL,
	"JobID" integer NOT NULL
)
;

CREATE TABLE "Loggedinuser"
(
	"Loggedinuser" varchar(200) NOT NULL,
	"LoginName" varchar(200) NOT NULL
)
;

CREATE TABLE "Nettordiscount"
(
	"Isnettordiscount" varchar(50),	-- end Which
	"Percentdiscount" numeric,
	"Other" varchar(50),
	"NettordiscountID" integer NOT NULL,
	"JobID" integer
)
;

CREATE TABLE "Nondoorvariation"
(
	"Description" varchar(50),	-- end VariantType
	"Costprice" numeric,
	"Sellprice" numeric,
	"Instructedby" varchar(50),
	"Instructiondate" timestamp without time zone,
	"Stage" varchar(50),
	"Type" varchar(50),
	"NondoorvariationID" integer NOT NULL,
	"LineitemID" integer
)
;

CREATE TABLE "Usergroup"
(
	"Name" varchar(50) NOT NULL,
	"Archivedon" timestamp with time zone,
	"UsergroupID" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Address" ADD CONSTRAINT "PK_Address"
	PRIMARY KEY ("AddressID")
;

ALTER TABLE "Applicationforpayment" ADD CONSTRAINT "PK_Applicationforpayment"
	PRIMARY KEY ("ApplicationforpaymentID")
;

ALTER TABLE "Auditrow" ADD CONSTRAINT "PK_Auditrow"
	PRIMARY KEY ("AuditrowID")
;

ALTER TABLE "Creditcheck" ADD CONSTRAINT "PK_Creditcheck"
	PRIMARY KEY ("CreditcheckID")
;

ALTER TABLE "Customer" ADD CONSTRAINT "PK_Customer"
	PRIMARY KEY ("CustomerID")
;

ALTER TABLE "Door" ADD CONSTRAINT "PK_Door"
	PRIMARY KEY ("DoorID")
;

CREATE INDEX "IXFK_Door_Doortype" ON "Door" ("DoortypeID" ASC)
;

ALTER TABLE "Doortype" ADD CONSTRAINT "PK_Doortype"
	PRIMARY KEY ("DoortypeID")
;

ALTER TABLE "Job" ADD CONSTRAINT "PK_Job"
	PRIMARY KEY ("JobID")
;

ALTER TABLE "Jobapproval" ADD CONSTRAINT "PK_Jobapproval"
	PRIMARY KEY ("JobapprovalID")
;

ALTER TABLE "Lineapplicationforpayment" ADD CONSTRAINT "PK_Lineapplicationforpayment"
	PRIMARY KEY ("LineapplicationforpaymentID")
;

ALTER TABLE "Lineitem" ADD CONSTRAINT "PK_Lineitem"
	PRIMARY KEY ("LineitemID")
;

ALTER TABLE "Loggedinuser" ADD CONSTRAINT "PK_Loggedinuser"
	PRIMARY KEY ("Loggedinuser")
;

ALTER TABLE "Nettordiscount" ADD CONSTRAINT "PK_Nettordiscount"
	PRIMARY KEY ("NettordiscountID")
;

ALTER TABLE "Nondoorvariation" ADD CONSTRAINT "PK_Nondoorvariation"
	PRIMARY KEY ("NondoorvariationID")
;

ALTER TABLE "Usergroup" ADD CONSTRAINT "PK_Usergroup"
	PRIMARY KEY ("UsergroupID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Auditrow" ADD CONSTRAINT "FK_Auditrow_Loggedinuser"
	FOREIGN KEY ("Loggedinuser") REFERENCES "Loggedinuser" ("Loggedinuser") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Auditrow" ADD CONSTRAINT "FK_Auditrow_Usergroup"
	FOREIGN KEY ("UsergroupID") REFERENCES "Usergroup" ("UsergroupID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Creditcheck" ADD CONSTRAINT "FK_Creditcheck_Job"
	FOREIGN KEY ("JobID") REFERENCES "Job" ("JobID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Creditcheck" ADD CONSTRAINT "FK_Creditcheck_Usergroup"
	FOREIGN KEY ("UsergroupID") REFERENCES "Usergroup" ("UsergroupID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_Address"
	FOREIGN KEY ("AddressId") REFERENCES "Address" ("AddressID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Door" ADD CONSTRAINT "FK_Door_Doortype"
	FOREIGN KEY ("DoortypeID") REFERENCES "Doortype" ("DoortypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Door" ADD CONSTRAINT "FK_Door_Lineitem"
	FOREIGN KEY ("LineitemID") REFERENCES "Lineitem" ("LineitemID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Job" ADD CONSTRAINT "FK_JobSite_Address"
	FOREIGN KEY ("Siteaddressid") REFERENCES "Address" ("AddressID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Job" ADD CONSTRAINT "FK_Job_Customer"
	FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("CustomerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Jobapproval" ADD CONSTRAINT "FK_Jobapproval_Usergroup"
	FOREIGN KEY ("UserGroupId") REFERENCES "Usergroup" ("UsergroupID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Jobapproval" ADD CONSTRAINT "FK_JobApproval_JobApproval"
	FOREIGN KEY ("JobID") REFERENCES "Job" ("JobID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lineapplicationforpayment" ADD CONSTRAINT "FK_Lineapplicationforpayment_Applicationforpayment"
	FOREIGN KEY ("ApplicationforpaymentID") REFERENCES "Applicationforpayment" ("ApplicationforpaymentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lineapplicationforpayment" ADD CONSTRAINT "FK_Lineapplicationforpayment_Lineitem"
	FOREIGN KEY ("LineItemId") REFERENCES "Lineitem" ("LineitemID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lineitem" ADD CONSTRAINT "FK_LineItem_LineItems"
	FOREIGN KEY ("JobID") REFERENCES "Job" ("JobID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Nettordiscount" ADD CONSTRAINT "FK_NettOrDiscount_NettOrDiscount"
	FOREIGN KEY ("JobID") REFERENCES "Job" ("JobID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Nondoorvariation" ADD CONSTRAINT "FK_NonDoorVariation_NonDoorVariation"
	FOREIGN KEY ("LineitemID") REFERENCES "Lineitem" ("LineitemID") ON DELETE No Action ON UPDATE No Action
;
